import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.161.0/examples/jsm/controls/OrbitControls.js';
import {TimeController} from './time_controller.js';
import {loadModernCountries,loadModernCountryBorders,loadPaleoCoastlines,loadPaleoLand,loadReconstructedCountry,loadReconstructedCountryBorders,makeCountryHighlight,disposeLineGroup,timelineBracket,timelineAges,prefetchPaleoFrames} from './geography.js?v=20260911-5';

const $=s=>document.querySelector(s);
const canvas=$('#globe'),loading=$('#loading'),status=$('#status'),debugLog=$('#debugLog'),followSelect=$('#followCountry'),countrySearch=$('#countrySearch'),bufferAmount=$('#bufferAmount'),bufferFill=$('#bufferFill'),bufferNote=$('#bufferNote'),countryToggle=$('#borders'),atmosphereToggle=$('#atmosphere');
const PREF_KEY='intheglobe.preferences.v1',BUFFER_KEY='intheglobe.timeline.buffer.v5',PRESENT=2026,PLAY_THRESHOLD=.5;
let preferences={};try{preferences=JSON.parse(localStorage.getItem(PREF_KEY)||'{}')||{}}catch{}
const savePreferences=patch=>{preferences={...preferences,...patch};try{localStorage.setItem(PREF_KEY,JSON.stringify(preferences))}catch{}};
const debug=(...a)=>{const t=a.map(v=>typeof v==='string'?v:JSON.stringify(v)).join(' ');if(debugLog){const e=document.createElement('div');e.textContent=`[${new Date().toLocaleTimeString()}] ${t}`;debugLog.appendChild(e);debugLog.scrollTop=debugLog.scrollHeight}console.log('[PastGlobe]',t)};
let time=null,bufferProgress=0,prefetchDone=false,prefetchRunning=false,modernCountries=null,countryBorders=null;
let paleoA=null,paleoB=null,paleoKey='',paleoRequest='',paleoSerial=0;
let borderA=null,borderB=null,borderKey='',borderRequest='',borderSerial=0,borderBusy=false;
let followA=null,followB=null,followKey='',followSerial=0,followTimer=0;
const readBuffer=total=>{try{const x=JSON.parse(localStorage.getItem(BUFFER_KEY)||'null');return x&&x.total===total&&Number.isFinite(x.completed)?Math.max(0,Math.min(1,x.completed/total)):0}catch{return 0}};
const writeBuffer=(done,total)=>{try{localStorage.setItem(BUFFER_KEY,JSON.stringify({version:5,total,completed:done,updatedAt:Date.now()}))}catch{}};
const setPlay=()=>{const b=time?.playButton;if(!b)return;const ready=bufferProgress>=PLAY_THRESHOLD;b.disabled=!ready;b.textContent=ready?(time.playing?'❚❚ Pause':'▶ Play'):'🚫 Play'};
const opacity=(g,v)=>{if(!g)return;g.traverse(o=>{if(!o.material)return;for(const m of(Array.isArray(o.material)?o.material:[o.material])){m.transparent=v<.999;m.opacity=v;m.depthWrite=v>.94}})};
const blend=(a,b,t)=>{if(!a)return;const x=Math.max(0,Math.min(1,t)),e=x*x*(3-2*x);opacity(a,1-e);if(b&&b!==a)opacity(b,e)};
window.addEventListener('error',e=>debug('WINDOW ERROR',e.error?.stack||e.message||e));window.addEventListener('unhandledrejection',e=>debug('UNHANDLED REJECTION',e.reason?.stack||e.reason||e));

let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'})}catch(e){status.textContent='WEBGL INITIALISATION FAILED';loading?.classList.add('done');throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x01050c);const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.05,100);camera.position.set(0,0,3.05);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.045;controls.enablePan=false;controls.minDistance=1.65;controls.maxDistance=5;
const earthGroup=new THREE.Group();earthGroup.name='InTheGlobeEarthGroup';scene.add(earthGroup);window.__intheglobeEarthGroup=earthGroup;
const earthMaterial=new THREE.MeshBasicMaterial({color:0xffffff});const earthSphere=new THREE.Mesh(new THREE.SphereGeometry(1,160,112),earthMaterial);earthGroup.add(earthSphere);
const paleoOcean=new THREE.Mesh(new THREE.SphereGeometry(.998,160,112),new THREE.MeshBasicMaterial({color:0x176d9a}));paleoOcean.visible=false;earthGroup.add(paleoOcean);
const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.045,96,64),new THREE.MeshBasicMaterial({color:0x4fcfff,transparent:true,opacity:.14,side:THREE.BackSide,depthWrite:false}));earthGroup.add(atmosphere);
new THREE.TextureLoader().load('https://threejs.org/examples/textures/planets/earth_atmos_2048.jpg',t=>{t.colorSpace=THREE.SRGBColorSpace;earthMaterial.map=t;earthMaterial.needsUpdate=true;debug('Modern Earth texture loaded')},undefined,e=>debug('Modern Earth texture failed',e?.message||e));

function countryByName(name){return modernCountries?.features.find(f=>f.properties?.name===name)||null}
function clearPaleo(){for(const f of[paleoA,paleoB])if(f){earthGroup.remove(f.land,f.lines);disposeLineGroup(f.land);disposeLineGroup(f.lines)}paleoA=paleoB=null;paleoKey=''}
function clearBorders(){for(const f of[borderA,borderB])if(f){earthGroup.remove(f);disposeLineGroup(f)}borderA=borderB=null;borderKey=''}
function clearFollow(){for(const f of[followA,followB])if(f){earthGroup.remove(f);disposeLineGroup(f)}followA=followB=null;followKey=''}
async function showPaleo(year){const b=timelineBracket(year),key=`${b.lower}:${b.upper}`;if(key===paleoKey&&paleoA)return;if(key===paleoRequest)return;paleoRequest=key;const serial=++paleoSerial;try{const [low,high]=await Promise.all([loadPaleoCoastlines(-b.lower*1e6,'CAO2024'),b.upper===b.lower?Promise.resolve(null):loadPaleoCoastlines(-b.upper*1e6,'CAO2024')]);const [lowLand,highLand]=await Promise.all([loadPaleoLand(-b.lower*1e6,'CAO2024'),b.upper===b.lower?Promise.resolve(null):loadPaleoLand(-b.upper*1e6,'CAO2024')]);if(serial!==paleoSerial){disposeLineGroup(low);disposeLineGroup(lowLand);if(high){disposeLineGroup(high);disposeLineGroup(highLand)};return}clearPaleo();paleoA={lines:low,land:lowLand};paleoB=high?{lines:high,land:highLand}:null;paleoKey=key;earthGroup.add(lowLand,low);if(high)earthGroup.add(highLand,high);lowLand.visible=low.visible=true;if(high){highLand.visible=high.visible=true}blend(lowLand,highLand,b.t);blend(low,high,b.t);debug('Historical frame rendered',key)}catch(e){if(serial===paleoSerial){status.textContent='CAO2024 DATA ERROR';debug(e?.stack||e)}}finally{if(paleoRequest===key)paleoRequest=''}}
async function showBorders(year){if(!modernCountries||!countryToggle?.checked)return;const b=timelineBracket(year),key=`${b.lower}:${b.upper}`;if(key===borderKey&&borderA)return;if(borderBusy&&borderRequest===key)return;borderRequest=key;borderBusy=true;const serial=++borderSerial;try{const [low,high]=await Promise.all([loadReconstructedCountryBorders(modernCountries,b.lower,'CAO2024',1.012),b.upper===b.lower?Promise.resolve(null):loadReconstructedCountryBorders(modernCountries,b.upper,'CAO2024',1.012)]);if(serial!==borderSerial){disposeLineGroup(low);if(high)disposeLineGroup(high);return}clearBorders();borderA=low;borderB=high;borderKey=key;earthGroup.add(low);if(high)earthGroup.add(high);low.visible=true;if(high)high.visible=true;blend(low,high,b.t);debug('Historical country borders rendered',key)}catch(e){if(serial===borderSerial)debug('Historical country borders failed',e?.stack||e)}finally{borderBusy=false;if(borderRequest===key)borderRequest=''}}
async function updateFollow(year){const c=countryByName(followSelect?.value);if(!c||year>PRESENT){clearFollow();return}if(year>=0){const key='present';if(key===followKey&&followA){followA.visible=true;return}const serial=++followSerial;try{const g=makeCountryHighlight(c,1.012);if(serial!==followSerial){disposeLineGroup(g);return}clearFollow();followA=g;followKey=key;earthGroup.add(g);g.visible=true;opacity(g,1)}catch(e){debug('Country highlight failed',e)}}else{const b=timelineBracket(year),key=`${c.properties.name}:${b.lower}:${b.upper}`;if(key===followKey&&followA){followA.visible=true;if(followB)followB.visible=true;blend(followA,followB,b.t);return}if(followTimer)return;const serial=++followSerial;try{followTimer=1;const [low,high]=await Promise.all([loadReconstructedCountry(c,b.lower,'CAO2024'),b.upper===b.lower?Promise.resolve(null):loadReconstructedCountry(c,b.upper,'CAO2024')]);if(serial!==followSerial){disposeLineGroup(low);if(high)disposeLineGroup(high);return}clearFollow();followA=low;followB=high;followKey=key;earthGroup.add(low);if(high)earthGroup.add(high);low.visible=true;if(high)high.visible=true;blend(low,high,b.t)}catch(e){debug('Country tracking failed',e)}finally{followTimer=0}}}
function updateGeography(year){const historical=year<0,future=year>PRESENT;earthSphere.visible=!historical&&!future;paleoOcean.visible=historical||future;atmosphere.visible=atmosphereToggle?.checked??true;if(future){status.textContent='SPECULATIVE FUTURE · PANGEA ULTIMA SCENARIO';for(const f of[paleoA,paleoB])if(f){f.land.visible=false;f.lines.visible=false}for(const f of[borderA,borderB])if(f)f.visible=false;for(const f of[followA,followB])if(f)f.visible=false;if(countryBorders)countryBorders.visible=false;return}if(!historical){status.textContent=`MODERN EARTH · ${Math.round(year).toLocaleString()} CE`;for(const f of[paleoA,paleoB])if(f){f.land.visible=false;f.lines.visible=false}for(const f of[borderA,borderB])if(f)f.visible=false;if(countryBorders)countryBorders.visible=!!countryToggle?.checked;updateFollow(year);return}status.textContent=`CAO2024 RECONSTRUCTION · ${Math.round(-year/1e6).toLocaleString()} Ma`;if(paleoA&&paleoKey===`${timelineBracket(year).lower}:${timelineBracket(year).upper}`){const b=timelineBracket(year);paleoA.land.visible=paleoA.lines.visible=true;if(paleoB){paleoB.land.visible=paleoB.lines.visible=true}blend(paleoA.land,paleoB?.land,b.t);blend(paleoA.lines,paleoB?.lines,b.t)}else void showPaleo(year);if(countryBorders)countryBorders.visible=false;for(const f of[borderA,borderB])if(f)f.visible=!!countryToggle?.checked;void showBorders(year);updateFollow(year)}
function filterCountries(){if(!modernCountries||!followSelect)return;const q=(countrySearch?.value||'').trim().toLowerCase(),current=followSelect.value||preferences.country||'';followSelect.innerHTML='<option value="">None</option>';for(const f of modernCountries.features.filter(f=>f.properties?.name).sort((a,b)=>a.properties.name.localeCompare(b.properties.name,'en'))){const n=f.properties.name;if(!q||n.toLowerCase().includes(q)){const o=document.createElement('option');o.value=n;o.textContent=n;followSelect.appendChild(o)}}if([...followSelect.options].some(o=>o.value===current))followSelect.value=current}

time=new TimeController({slider:$('#timeline'),yearInput:$('#yearInput'),yearOutput:$('#year'),epoch:$('#epoch'),playButton:$('#play'),onChange:year=>{savePreferences({year:Math.round(year)});updateGeography(year)}});
const originalToggle=time.toggle.bind(time);time.toggle=()=>{if(!time.playing&&bufferProgress<PLAY_THRESHOLD){setPlay();return}originalToggle();savePreferences({playing:time.playing,speed:time.speed});setPlay()};if(Number.isFinite(preferences.speed))time.speed=preferences.speed;if(Number.isFinite(preferences.year))time.setYear(preferences.year);setPlay();
time.slider?.addEventListener('input',()=>savePreferences({playing:false}));
followSelect?.addEventListener('change',()=>{savePreferences({country:followSelect.value||''});followSerial++;clearFollow();updateFollow(time.year)});countrySearch?.addEventListener('input',filterCountries);
atmosphereToggle?.addEventListener('change',e=>{atmosphere.visible=e.target.checked;savePreferences({atmosphere:e.target.checked})});countryToggle?.addEventListener('change',()=>{savePreferences({borders:countryToggle.checked});updateGeography(time.year)});$('#jumpPresent')?.addEventListener('click',()=>time.setYear(PRESENT));document.querySelectorAll('#speeds [data-speed]').forEach(b=>b.addEventListener('click',()=>savePreferences({speed:time.speed})));$('#collapse')?.addEventListener('click',()=>$('#hud')?.classList.add('hidden'));$('#dock')?.addEventListener('click',()=>$('#hud')?.classList.remove('hidden'));canvas.addEventListener('dblclick',()=>{controls.reset();camera.position.set(0,0,3.05)});addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});
const backgroundAges=timelineAges();bufferProgress=readBuffer(backgroundAges.length);if(bufferAmount)bufferAmount.textContent=`${Math.round(bufferProgress*100)}%`;if(bufferFill)bufferFill.style.width=`${bufferProgress*100}%`;if(bufferNote)bufferNote.textContent=bufferProgress>=1?'Historical frames ready from saved browser cache':`Resuming background buffer · ${Math.round(bufferProgress*100)}% already completed`;setPlay();
(async()=>{if(prefetchRunning)return;prefetchRunning=true;try{const complete=await prefetchPaleoFrames(backgroundAges,'CAO2024',2,(p,d,t)=>{bufferProgress=Math.max(bufferProgress,p);writeBuffer(d,t);if(bufferAmount)bufferAmount.textContent=`${Math.round(bufferProgress*100)}%`;if(bufferFill)bufferFill.style.width=`${bufferProgress*100}%`;setPlay()});if(complete){prefetchDone=true;bufferProgress=1;writeBuffer(backgroundAges.length,backgroundAges.length);if(bufferNote)bufferNote.textContent=`Historical frames ready · ${backgroundAges.length} cached`;setPlay()}}catch(e){debug('Background buffer failed',e?.message||e)}})();
loadModernCountries().then(c=>{modernCountries=c;filterCountries();if(preferences.country&&countryByName(preferences.country))followSelect.value=preferences.country;return loadModernCountryBorders()}).then(g=>{countryBorders=g;earthGroup.add(g);countryBorders.visible=!!countryToggle?.checked&&time.year>=0&&time.year<=PRESENT}).catch(e=>debug('Modern country layer failed',e?.message||e));
requestAnimationFrame(function frame(now){time.update(now);controls.update();renderer.render(scene,camera);requestAnimationFrame(frame)});updateGeography(time.year);loading?.classList.add('done');debug('Stable PastGlobe app started',`year=${time.year}`);
