import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';
import {feature} from 'https://cdn.jsdelivr.net/npm/topojson-client@3/+esm';
const GWS='https://gws.gplates.org/reconstruct/';const MODERN_COUNTRIES='https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json';
function geoPoint(lon,lat,r=1){const a=THREE.MathUtils.degToRad(lat),b=THREE.MathUtils.degToRad(lon);return new THREE.Vector3(Math.cos(a)*Math.cos(b),Math.sin(a),Math.cos(a)*Math.sin(b)).multiplyScalar(r)}
function geometries(g,out=[]){if(!g)return out;if(g.type==='FeatureCollection')g.features.forEach(f=>geometries(f.geometry,out));else if(g.type==='Feature')geometries(g.geometry,out);else out.push(g);return out}
function polygonRings(geometry){const out=[];for(const g of geometries(geometry)){if(g.type==='Polygon')out.push(g.coordinates);else if(g.type==='MultiPolygon')g.coordinates.forEach(p=>out.push(p))}return out}
function addGeometryLines(group,geometry,radius,material){for(const g of geometries(geometry)){const lines=g.type==='LineString'?[g.coordinates]:g.type==='MultiLineString'?g.coordinates:g.type==='Polygon'?g.coordinates:g.type==='MultiPolygon'?g.coordinates.flat(1):[];for(const ring of lines){if(!ring||ring.length<2)continue;const pts=ring.map(([lon,lat])=>geoPoint(lon,lat,radius));group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),material))}}}
function landMesh(data,radius=1.002,material){const group=new THREE.Group();const mat=material||new THREE.MeshStandardMaterial({color:0x667b55,roughness:.92,metalness:0,side:THREE.DoubleSide});for(const rings of polygonRings(data)){if(!rings.length||rings[0].length<3)continue;const flat=rings.flat();const contour=flat.slice(0,rings[0].length).map(([lon,lat])=>new THREE.Vector2(lon,lat));const holes=rings.slice(1).map(r=>r.map(([lon,lat])=>new THREE.Vector2(lon,lat)));const tris=THREE.ShapeUtils.triangulateShape(contour,holes);const positions=[];for(const tri of tris)for(const idx of tri){const [lon,lat]=flat[idx];const p=geoPoint(lon,lat,radius);positions.push(p.x,p.y,p.z)}if(!positions.length)continue;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.computeVertexNormals();group.add(new THREE.Mesh(g,mat))}return group}
let modernCountriesPromise=null;
export async function loadModernCountries(){if(!modernCountriesPromise)modernCountriesPromise=fetch(MODERN_COUNTRIES,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(`Country data HTTP ${r.status}`);return r.json()}).then(topo=>feature(topo,topo.objects.countries));return modernCountriesPromise}
export async function loadModernCountryBorders(radius=1.006){const countries=await loadModernCountries();const group=new THREE.Group();const material=new THREE.LineBasicMaterial({color:0xb7d8e8,transparent:true,opacity:.52,depthWrite:false});addGeometryLines(group,countries,radius,material);return group}
const paleoCache=new Map();async function getPaleoData(year,model='CAO2024'){const age=Math.max(0,Math.min(1800,-year/1e6));const key=`${model}:${Math.round(age*10)/10}`;if(paleoCache.has(key))return paleoCache.get(key);const url=`${GWS}coastlines/?time=${encodeURIComponent(age)}&model=${encodeURIComponent(model)}`;const promise=fetch(url,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(`GPlates HTTP ${r.status}`);return r.json()});paleoCache.set(key,promise);return promise}
export async function loadPaleoCoastlines(year,model='CAO2024',radius=1.008){const data=await getPaleoData(year,model);const group=new THREE.Group();const material=new THREE.LineBasicMaterial({color:0xd9f3e6,transparent:true,opacity:.82,depthWrite:false});addGeometryLines(group,data,radius,material);return group}
export async function loadPaleoLand(year,model='CAO2024',radius=1.002){const data=await getPaleoData(year,model);return landMesh(data,radius)}
export function timelineAges(){const ages=[];for(let a=0;a<=50;a+=1)ages.push(a);for(let a=52.5;a<=150;a+=2.5)ages.push(Number(a.toFixed(1)));for(let a=155;a<=600;a+=5)ages.push(a);return ages}
export function timelineBracket(year){const age=Math.max(0,Math.min(600,-Number(year||0)/1e6));const ages=timelineAges();if(age<=ages[0])return{lower:ages[0],upper:ages[0],t:0};if(age>=ages[ages.length-1])return{lower:ages[ages.length-1],upper:ages[ages.length-1],t:0};for(let i=0;i<ages.length-1;i++){const lower=ages[i],upper=ages[i+1];if(age>=lower&&age<=upper)return{lower,upper,t:(age-lower)/(upper-lower)}}return{lower:0,upper:0,t:0}}
export async function prefetchPaleoFrames(agesMa,model='CAO2024',concurrency=8,onProgress){const ages=[...new Set(agesMa.map(Number).filter(Number.isFinite).map(a=>Math.max(0,Math.min(600,a))))].sort((a,b)=>a-b);let done=0,cursor=0;const worker=async()=>{while(true){const i=cursor++;if(i>=ages.length)return;try{await getPaleoData(-ages[i]*1e6,model)}catch{}finally{done++;onProgress?.(done/ages.length,done,ages.length)}}};await Promise.all(Array.from({length:Math.min(concurrency,ages.length)},worker));return true}
const reconstructedCountryCache=new Map();
export async function reconstructFeatureCollection(fc,timeMa,model='CAO2024'){const key=`${model}:${Math.round(timeMa*2)/2}:${fc.features.map(f=>f.properties?.name||'').join('|')}`;if(reconstructedCountryCache.has(key))return reconstructedCountryCache.get(key);const body=new URLSearchParams();body.set('feature_collection',JSON.stringify(fc));body.set('time',String(timeMa));body.set('model',model);const promise=fetch(`${GWS}reconstruct_feature_collection`,{method:'POST',body}).then(async r=>{if(!r.ok)throw new Error(`GPlates reconstruction HTTP ${r.status}`);return r.json()});reconstructedCountryCache.set(key,promise);return promise}
export async function loadReconstructedCountry(countryFeature,timeMa,model='CAO2024',radius=1.016){const data=await reconstructFeatureCollection({type:'FeatureCollection',features:[countryFeature]},timeMa,model);return makeCountryHighlight(data,radius)}
export async function prefetchReconstructedCountryFrames(countryFeature,agesMa,model='CAO2024',concurrency=6,onProgress){const ages=[...new Set(agesMa.map(Number).filter(Number.isFinite).map(a=>Math.max(0,Math.min(600,a))))].sort((a,b)=>a-b);const fc={type:'FeatureCollection',features:[countryFeature]};let done=0,cursor=0;const worker=async()=>{while(true){const i=cursor++;if(i>=ages.length)return;try{await reconstructFeatureCollection(fc,ages[i],model)}catch{}finally{done++;onProgress?.(done/ages.length,done,ages.length)}}};await Promise.all(Array.from({length:Math.min(concurrency,ages.length)},worker));return true}
export function makeCountryHighlight(data,radius=1.012){const group=new THREE.Group();const fill=landMesh(data,radius,new THREE.MeshBasicMaterial({color:0xff1493,transparent:true,opacity:.42,side:THREE.DoubleSide,depthWrite:false}));group.add(fill);addGeometryLines(group,data,radius+.006,new THREE.LineBasicMaterial({color:0xff1493,transparent:true,opacity:1,depthWrite:false}));return group}
export function disposeLineGroup(group){if(!group)return;group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}})}
export function paleogeographyAge(year){return Math.max(0,-year/1e6)}
