import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';
import {feature} from 'https://cdn.jsdelivr.net/npm/topojson-client@3/+esm';
const GWS='https://gws.gplates.org/reconstruct/';const MODERN_COUNTRIES='https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json';const CACHE_DB='intheglobe-cache-v3';const CACHE_STORE='json';const CACHE_VERSION=3;const TIMELINE_META='intheglobe.timeline.cache.v3';
// Standard equirectangular longitude/latitude mapping for Three.js SphereGeometry.
// Horizontal mouse-drag direction is inverted separately in index.html via OrbitControls.rotateLeft.
function geoPoint(lon,lat,r=1){const a=THREE.MathUtils.degToRad(lat),b=THREE.MathUtils.degToRad(lon);return new THREE.Vector3(Math.cos(a)*Math.cos(b),Math.sin(a),-Math.cos(a)*Math.sin(b)).multiplyScalar(r)}
function geometries(g,out=[]){if(!g)return out;if(g.type==='FeatureCollection')g.features.forEach(f=>geometries(f.geometry,out));else if(g.type==='Feature')geometries(g.geometry,out);else out.push(g);return out}
function polygonRings(geometry){const out=[];for(const g of geometries(geometry)){if(g.type==='Polygon')out.push(g.coordinates);else if(g.type==='MultiPolygon')g.coordinates.forEach(p=>out.push(p))}return out}
function unwrapRing(ring){if(!ring?.length)return[];const out=[];let previous=Number(ring[0][0]);out.push([previous,Number(ring[0][1])]);for(let i=1;i<ring.length;i++){let lon=Number(ring[i][0]),lat=Number(ring[i][1]);while(lon-previous>180)lon-=360;while(lon-previous<-180)lon+=360;out.push([lon,lat]);previous=lon}return out}
function shiftedHoleRing(ring,anchor){const unwrapped=unwrapRing(ring);if(!unwrapped.length)return[];const shift=360*Math.round((anchor-unwrapped[0][0])/360);return unwrapped.map(([lon,lat])=>[lon+shift,lat])}
function addGeometryLines(group,geometry,radius,material){const positions=[];for(const g of geometries(geometry)){const lines=g.type==='LineString'?[g.coordinates]:g.type==='MultiLineString'?g.coordinates:g.type==='Polygon'?g.coordinates:g.type==='MultiPolygon'?g.coordinates.flat(1):[];for(const ring of lines){if(!ring||ring.length<2)continue;for(let i=0;i<ring.length-1;i++){const a=geoPoint(ring[i][0],ring[i][1],radius),b=geoPoint(ring[i+1][0],ring[i+1][1],radius);positions.push(a.x,a.y,a.z,b.x,b.y,b.z)}}}if(!positions.length)return;const geometryBuffer=new THREE.BufferGeometry();geometryBuffer.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometryBuffer.computeBoundingSphere();const line=new THREE.LineSegments(geometryBuffer,material);line.renderOrder=20;group.add(line)}
function cleanRing(ring){const out=[];for(const point of ring||[]){const lon=Number(point[0]),lat=Number(point[1]);if(!Number.isFinite(lon)||!Number.isFinite(lat))continue;if(!out.length||Math.abs(lon-out[out.length-1][0])>1e-10||Math.abs(lat-out[out.length-1][1])>1e-10)out.push([lon,lat])}if(out.length>1&&Math.abs(out[0][0]-out[out.length-1][0])<1e-10&&Math.abs(out[0][1]-out[out.length-1][1])<1e-10)out.pop();return out}
function landMesh(data,radius=1.002,material,ignoreHoles=false){const group=new THREE.Group();const mat=material||new THREE.MeshBasicMaterial({color:0x9eb48d,side:THREE.DoubleSide});const positions=[];for(const rings of polygonRings(data)){const outer=cleanRing(unwrapRing(rings[0]));if(outer.length<3)continue;const anchor=outer[0][0];const holes=ignoreHoles?[]:rings.slice(1).map(r=>cleanRing(shiftedHoleRing(r,anchor))).filter(r=>r.length>=3);const all=[outer,...holes];const contour=outer.map(([lon,lat])=>new THREE.Vector2(lon,lat));const holePoints=holes.map(r=>r.map(([lon,lat])=>new THREE.Vector2(lon,lat)));let tris=THREE.ShapeUtils.triangulateShape(contour,holePoints);if(!tris.length&&holes.length)tris=THREE.ShapeUtils.triangulateShape(contour,[]);if(!tris.length)continue;const flat=all.flat();for(const tri of tris)for(const idx of tri){const point=flat[idx];if(!point)continue;const [lon,lat]=point;const p=geoPoint(lon,lat,radius);positions.push(p.x,p.y,p.z)}}if(!positions.length)return group;const geometryBuffer=new THREE.BufferGeometry();geometryBuffer.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometryBuffer.computeBoundingSphere();const mesh=new THREE.Mesh(geometryBuffer,mat);mesh.renderOrder=10;group.add(mesh);return group}
function openPersistentDB(){if(typeof indexedDB==='undefined')return Promise.resolve(null);if(openPersistentDB.promise)return openPersistentDB.promise;openPersistentDB.promise=new Promise((resolve,reject)=>{const request=indexedDB.open(CACHE_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(CACHE_STORE))db.createObjectStore(CACHE_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('IndexedDB unavailable'))});return openPersistentDB.promise}
async function persistentGet(key){try{const db=await openPersistentDB();if(!db)return null;return await new Promise((resolve,reject)=>{const tx=db.transaction(CACHE_STORE,'readonly');const req=tx.objectStore(CACHE_STORE).get(key);req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>reject(req.error||new Error('IndexedDB read failed'))})}catch{return null}}
async function persistentPut(key,value){try{const db=await openPersistentDB();if(!db)return;await new Promise((resolve,reject)=>{const tx=db.transaction(CACHE_STORE,'readwrite');tx.objectStore(CACHE_STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error('IndexedDB write failed'))})}catch{}}
function timelineMetaSave(ready,total){try{localStorage.setItem(TIMELINE_META,JSON.stringify({version:CACHE_VERSION,ready,total,updatedAt:Date.now()}))}catch{}}
export function timelineCachedProgress(total){try{const raw=localStorage.getItem(TIMELINE_META);const meta=raw?JSON.parse(raw):null;if(meta?.version===CACHE_VERSION&&meta.total===total)return Math.max(0,Math.min(1,Number(meta.ready||0)/total))}catch{}return 0}
let modernCountriesPromise=null;
export async function loadModernCountries(){if(!modernCountriesPromise)modernCountriesPromise=fetch(MODERN_COUNTRIES,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(`Country data HTTP ${r.status}`);return r.json()}).then(topo=>feature(topo,topo.objects.countries));return modernCountriesPromise}
export async function loadModernCountryBorders(radius=1.006){const countries=await loadModernCountries();const group=new THREE.Group();const material=new THREE.LineBasicMaterial({color:0xb7d8e8,transparent:true,opacity:.72,depthWrite:false});addGeometryLines(group,countries,radius,material);return group}
export async function loadModernCountryOverlay(radius=1.012){const countries=await loadModernCountries();const group=new THREE.Group();const fill=landMesh(countries,radius,new THREE.MeshBasicMaterial({color:0x168cff,transparent:true,opacity:.24,side:THREE.DoubleSide,depthWrite:false}),true);fill.renderOrder=10;group.add(fill);addGeometryLines(group,countries,radius+.006,new THREE.LineBasicMaterial({color:0x46b7ff,transparent:true,opacity:.9,depthWrite:false}));group.renderOrder=10;return group}
const paleoCache=new Map();
async function getPaleoData(year,model='CAO2024'){const age=Math.max(0,Math.min(1800,-year/1e6));const key=`paleo:${model}:${Math.round(age*10)/10}`;if(paleoCache.has(key))return paleoCache.get(key);const promise=(async()=>{const persisted=await persistentGet(key);if(persisted)return persisted;const url=`${GWS}coastlines/?time=${encodeURIComponent(age)}&model=${encodeURIComponent(model)}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`GPlates HTTP ${r.status}`);const data=await r.json();persistentPut(key,data);return data})();paleoCache.set(key,promise);return promise}
export async function loadPaleoCoastlines(year,model='CAO2024',radius=1.008){const data=await getPaleoData(year,model);const group=new THREE.Group();const material=new THREE.LineBasicMaterial({color:0xd9f3e6,transparent:true,opacity:.9,depthWrite:false});addGeometryLines(group,data,radius,material);return group}
export async function loadPaleoLand(year,model='CAO2024',radius=1.002){const data=await getPaleoData(year,model);return landMesh(data,radius,new THREE.MeshBasicMaterial({color:0x9eb48d,side:THREE.DoubleSide}))}
export function timelineAges(){const ages=[];for(let a=0;a<=50;a+=1)ages.push(a);for(let a=52.5;a<=150;a+=2.5)ages.push(Number(a.toFixed(1)));for(let a=155;a<=600;a+=5)ages.push(a);return ages}
export function timelineBracket(year){const age=Math.max(0,Math.min(600,-Number(year||0)/1e6));const ages=timelineAges();if(age<=ages[0])return{lower:ages[0],upper:ages[0],t:0};if(age>=ages[ages.length-1])return{lower:ages[ages.length-1],upper:ages[ages.length-1],t:0};for(let i=0;i<ages.length-1;i++){const lower=ages[i],upper=ages[i+1];if(age>=lower&&age<=upper)return{lower,upper,t:(age-lower)/(upper-lower)}}return{lower:0,upper:0,t:0}}
export async function prefetchPaleoFrames(agesMa,model='CAO2024',concurrency=20,onProgress){const ages=[...new Set(agesMa.map(Number).filter(Number.isFinite).map(a=>Math.max(0,Math.min(600,a))))].sort((a,b)=>a-b);let completed=0,cursor=0;const worker=async()=>{while(true){const i=cursor++;if(i>=ages.length)return;try{await getPaleoData(-ages[i]*1e6,model);completed++}catch{}finally{timelineMetaSave(completed,ages.length);onProgress?.(completed/ages.length,completed,ages.length)}}};await Promise.all(Array.from({length:Math.min(concurrency,ages.length)},worker));return completed===ages.length}
const reconstructedCountryCache=new Map();
function countryParts(countryFeature){const geometry=countryFeature?.geometry;if(!geometry)return[];if(geometry.type==='MultiPolygon')return geometry.coordinates.map((coordinates,index)=>({type:'Feature',properties:{...(countryFeature.properties||{}),__countryPart:index+1},geometry:{type:'Polygon',coordinates}}));return[{...countryFeature,properties:{...(countryFeature.properties||{})}}]}
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
async function reconstructFeatureCollection(fc,timeMa,model='CAO2024'){const key=`country:${model}:${Math.round(timeMa*2)/2}:${hashText(JSON.stringify(fc.features.map(f=>f.geometry)))}`;if(reconstructedCountryCache.has(key))return reconstructedCountryCache.get(key);const persisted=await persistentGet(key);if(persisted){reconstructedCountryCache.set(key,Promise.resolve(persisted));return persisted}const body=new URLSearchParams();body.set('feature_collection',JSON.stringify(fc));body.set('time',String(timeMa));body.set('model',model);const promise=fetch(`${GWS}reconstruct_feature_collection`,{method:'POST',body}).then(async r=>{if(!r.ok)throw new Error(`GPlates reconstruction HTTP ${r.status}`);const data=await r.json();persistentPut(key,data);return data});reconstructedCountryCache.set(key,promise);return promise}
export async function loadReconstructedCountry(countryFeature,timeMa,model='CAO2024',radius=1.016){const parts=countryParts(countryFeature);if(!parts.length)throw new Error('Country has no reconstructable geometry');const reconstructed=await Promise.all(parts.map(part=>reconstructFeatureCollection({type:'FeatureCollection',features:[part]},timeMa,model)));return makeCountryHighlight({type:'FeatureCollection',features:reconstructed.flatMap(fc=>fc.features||[])},radius)}
export async function prefetchReconstructedCountryFrames(countryFeature,agesMa,model='CAO2024',concurrency=12,onProgress){const ages=[...new Set(agesMa.map(Number).filter(Number.isFinite).map(a=>Math.max(0,Math.min(600,a))))].sort((a,b)=>a-b);const parts=countryParts(countryFeature);let done=0,cursor=0;const worker=async()=>{while(true){const i=cursor++;if(i>=ages.length)return;try{await Promise.all(parts.map(part=>reconstructFeatureCollection({type:'FeatureCollection',features:[part]},ages[i],model)));done++}catch{}finally{onProgress?.(done/ages.length,done,ages.length)}}};await Promise.all(Array.from({length:Math.min(concurrency,ages.length)},worker));return done===ages.length}
export function makeCountryHighlight(data,radius=1.012){const group=new THREE.Group();const fill=landMesh(data,radius,new THREE.MeshBasicMaterial({color:0xff1493,transparent:true,opacity:.42,side:THREE.DoubleSide,depthWrite:false}));group.add(fill);addGeometryLines(group,data,radius+.006,new THREE.LineBasicMaterial({color:0xff1493,transparent:true,opacity:1,depthWrite:false}));return group}
export function disposeLineGroup(group){if(!group)return;group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}})}
export function paleogeographyAge(year){return Math.max(0,-year/1e6)}
