import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';
import {feature} from 'https://cdn.jsdelivr.net/npm/topojson-client@3/+esm';
import {geoEquirectangular,geoPath} from 'https://cdn.jsdelivr.net/npm/d3-geo@3/+esm';
const GWS_SERVERS=['https://gws.gplates.org/reconstruct/','https://gws1.gplates.org/reconstruct/','https://gws2.gplates.org/reconstruct/'];
const MODERN_COUNTRIES='https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json';
const CACHE_DB='intheglobe-cache-v3',CACHE_STORE='json',MAX_LIVE_PALEO_DATA=6,MAX_AGE=600;
function geoPoint(lon,lat,r=1){const a=THREE.MathUtils.degToRad(lat),b=THREE.MathUtils.degToRad(lon);return new THREE.Vector3(Math.cos(a)*Math.cos(b),Math.sin(a),-Math.cos(a)*Math.sin(b)).multiplyScalar(r)}
function geometries(g,out=[]){if(!g)return out;if(g.type==='FeatureCollection')g.features.forEach(f=>geometries(f.geometry,out));else if(g.type==='Feature')geometries(g.geometry,out);else if(g.type==='GeometryCollection')g.geometries?.forEach(x=>geometries(x,out));else out.push(g);return out}
function addGeometryLines(group,geometry,radius,material){const positions=[];for(const g of geometries(geometry)){const lines=g.type==='LineString'?[g.coordinates]:g.type==='MultiLineString'?g.coordinates:g.type==='Polygon'?g.coordinates:g.type==='MultiPolygon'?g.coordinates.flat(1):[];for(const ring of lines){if(!Array.isArray(ring)||ring.length<2)continue;for(let i=0;i<ring.length-1;i++){const p=ring[i],q=ring[i+1];if(!Array.isArray(p)||!Array.isArray(q))continue;const a=geoPoint(Number(p[0]),Number(p[1]),radius),b=geoPoint(Number(q[0]),Number(q[1]),radius);positions.push(a.x,a.y,a.z,b.x,b.y,b.z)}}}if(!positions.length)return;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));const line=new THREE.LineSegments(g,material);line.renderOrder=20;group.add(line)}
function makeGeoTexture(data,{fill=null,stroke='rgba(70,183,255,.9)',lineWidth=2,size=4096}={}){const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size/2;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas 2D unavailable');const projection=geoEquirectangular().scale(size/(2*Math.PI)).translate([size/2,canvas.height/2]);const path=geoPath(projection,ctx);ctx.clearRect(0,0,canvas.width,canvas.height);if(fill)ctx.fillStyle=fill;if(stroke&&lineWidth>0){ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.lineJoin='round';ctx.lineCap='round'}if(data){ctx.beginPath();path(data);if(fill)ctx.fill('evenodd');if(stroke&&lineWidth>0)ctx.stroke()}const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.needsUpdate=true;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;texture.generateMipmaps=false;return texture}
function textureGlobe(data,radius,options={}){const group=new THREE.Group(),texture=makeGeoTexture(data,options),material=new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,side:THREE.DoubleSide});const mesh=new THREE.Mesh(new THREE.SphereGeometry(radius,160,112),material);mesh.renderOrder=15;group.add(mesh);group.userData.__texture=texture;return group}
function openPersistentDB(){if(typeof indexedDB==='undefined')return Promise.resolve(null);if(openPersistentDB.promise)return openPersistentDB.promise;openPersistentDB.promise=new Promise((resolve,reject)=>{const request=indexedDB.open(CACHE_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(CACHE_STORE))db.createObjectStore(CACHE_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('IndexedDB unavailable'))});return openPersistentDB.promise}
async function persistentGet(key){try{const db=await openPersistentDB();if(!db)return null;return await new Promise((resolve,reject)=>{const tx=db.transaction(CACHE_STORE,'readonly'),req=tx.objectStore(CACHE_STORE).get(key);req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>reject(req.error||new Error('IndexedDB read failed'))})}catch{return null}}
async function persistentPut(key,value){try{const db=await openPersistentDB();if(!db)return;await new Promise((resolve,reject)=>{const tx=db.transaction(CACHE_STORE,'readwrite');tx.objectStore(CACHE_STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error('IndexedDB write failed'))})}catch{}}
let modernCountriesPromise=null;
export async function loadModernCountries(){if(!modernCountriesPromise)modernCountriesPromise=fetch(MODERN_COUNTRIES,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(`Country data HTTP ${r.status}`);return r.json()}).then(t=>feature(t,t.objects.countries));return modernCountriesPromise}
export async function loadModernCountryBorders(radius=1.006){return textureGlobe(await loadModernCountries(),radius,{fill:null,stroke:'rgba(183,216,232,.7)',lineWidth:2,size:2048})}
const paleoCache=new Map(),paleoPromiseCache=new Map();
function rememberPaleo(k,v){paleoCache.delete(k);paleoCache.set(k,v);while(paleoCache.size>MAX_LIVE_PALEO_DATA)paleoCache.delete(paleoCache.keys().next().value)}
async function fetchPaleo(age,model){for(const base of GWS_SERVERS){for(let attempt=0;attempt<2;attempt++){try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),45000);let r;try{r=await fetch(`${base}coastlines/?time=${encodeURIComponent(age)}&model=${encodeURIComponent(model)}`,{cache:'no-store',signal:controller.signal})}finally{clearTimeout(timer)}if(!r.ok)throw new Error(`GPlates HTTP ${r.status}`);const data=await r.json();if(data?.type!=='FeatureCollection'||!Array.isArray(data.features))throw new Error('Invalid GPlates GeoJSON');return data}catch(error){if(attempt===1)console.warn('[PastGlobe] paleo request failed',base,error)}}}throw new Error('All GPlates servers failed')}
async function getPaleoData(year,model='CAO2024'){const age=Math.max(0,Math.min(MAX_AGE,-year/1e6)),key=`paleo:${model}:${Math.round(age*10)/10}`;if(paleoCache.has(key)){const v=paleoCache.get(key);paleoCache.delete(key);paleoCache.set(key,v);return v}if(paleoPromiseCache.has(key))return paleoPromiseCache.get(key);const promise=(async()=>{const persisted=await persistentGet(key);if(persisted){rememberPaleo(key,persisted);return persisted}const data=await fetchPaleo(age,model);await persistentPut(key,data);rememberPaleo(key,data);return data})();paleoPromiseCache.set(key,promise);try{return await promise}finally{paleoPromiseCache.delete(key)}}
export async function loadPaleoLand(year,model='CAO2024',radius=1.002){return textureGlobe(await getPaleoData(year,model),radius,{fill:'rgba(158,180,141,1)',stroke:null,lineWidth:0,size:4096})}
export async function loadPaleoCoastlines(year,model='CAO2024',radius=1.008){const group=new THREE.Group();addGeometryLines(group,await getPaleoData(year,model),radius,new THREE.LineBasicMaterial({color:0xe5f5ec,transparent:true,opacity:.95,depthWrite:false}));return group}
export function timelineAges(){const ages=[];for(let a=0;a<=50;a++)ages.push(a);for(let a=52.5;a<=150;a+=2.5)ages.push(Number(a.toFixed(1)));for(let a=155;a<=600;a+=5)ages.push(a);return ages}
export function timelineBracket(year){const age=Math.max(0,Math.min(MAX_AGE,-Number(year||0)/1e6)),ages=timelineAges();if(age<=0)return{lower:0,upper:0,t:0};for(let i=0;i<ages.length-1;i++)if(age>=ages[i]&&age<=ages[i+1])return{lower:ages[i],upper:ages[i+1],t:(age-ages[i])/(ages[i+1]-ages[i])};return{lower:600,upper:600,t:0}}
export async function prefetchPaleoFrames(ages,model='CAO2024',concurrency=2,onProgress=()=>{}){const list=[...ages];if(!list.length)return true;let cursor=0,ok=0;const worker=async()=>{while(true){const i=cursor++;if(i>=list.length)return;try{await getPaleoData(-list[i]*1e6,model);ok++;onProgress(ok/list.length,ok,list.length,list[i])}catch(error){console.warn('[PastGlobe] failed paleo frame',list[i],error)}}};await Promise.all(Array.from({length:Math.min(Math.max(1,concurrency),list.length)},worker));return ok===list.length}
const reconstructedCountryCache=new Map(),reconstructedCountryPromiseCache=new Map();
function countryParts(countryFeature){const g=countryFeature?.geometry;if(!g)return[];if(g.type==='MultiPolygon')return g.coordinates.map((coordinates,index)=>({type:'Feature',properties:{...(countryFeature.properties||{}),__countryPart:index+1},geometry:{type:'Polygon',coordinates}}));return[{...countryFeature}]}
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
async function reconstructFeatureCollection(fc,timeMa,model='CAO2024'){const key=`country:${model}:${Math.round(timeMa*2)/2}:${hashText(JSON.stringify(fc.features.map(f=>f.geometry)))}`;if(reconstructedCountryCache.has(key))return reconstructedCountryCache.get(key);if(reconstructedCountryPromiseCache.has(key))return reconstructedCountryPromiseCache.get(key);const promise=(async()=>{const persisted=await persistentGet(key);if(persisted){reconstructedCountryCache.set(key,persisted);return persisted}const body=new URLSearchParams({feature_collection:JSON.stringify(fc),time:String(timeMa),model});let lastError=null;for(const base of GWS_SERVERS){try{const r=await fetch(`${base}reconstruct_feature_collection`,{method:'POST',body,cache:'no-store'});if(!r.ok)throw new Error(`GPlates reconstruction HTTP ${r.status}`);const data=await r.json();if(data?.type!=='FeatureCollection'||!Array.isArray(data.features))throw new Error('Invalid reconstructed GeoJSON');await persistentPut(key,data);reconstructedCountryCache.set(key,data);return data}catch(error){lastError=error}}throw lastError||new Error('Country reconstruction failed')})();reconstructedCountryPromiseCache.set(key,promise);try{return await promise}finally{reconstructedCountryPromiseCache.delete(key)}}
export async function loadReconstructedCountry(countryFeature,timeMa,model='CAO2024',radius=1.016){const parts=countryParts(countryFeature);if(!parts.length)throw new Error('Country has no reconstructable geometry');const reconstructed=await Promise.all(parts.map(part=>reconstructFeatureCollection({type:'FeatureCollection',features:[part]},timeMa,model)));return makeCountryHighlight({type:'FeatureCollection',features:reconstructed.flatMap(fc=>fc.features||[])},radius)}
const borderGroupCache=new Map(),borderGroupPromiseCache=new Map();
export async function loadReconstructedCountryBorders(countryCollection,timeMa,model='CAO2024',radius=1.012){if(!countryCollection?.features?.length)throw new Error('No modern country geometry available');const key=`borders:${model}:${Math.round(timeMa*2)/2}:${hashText(JSON.stringify(countryCollection.features.map(f=>f.geometry)))}`;if(borderGroupCache.has(key))return borderGroupCache.get(key);if(borderGroupPromiseCache.has(key))return borderGroupPromiseCache.get(key);const promise=(async()=>{const reconstructed=await reconstructFeatureCollection({type:'FeatureCollection',features:countryCollection.features},timeMa,model);const group=new THREE.Group();addGeometryLines(group,reconstructed,radius,new THREE.LineBasicMaterial({color:0xb7d8e8,transparent:true,opacity:.82,depthWrite:false}));borderGroupCache.set(key,group);return group})();borderGroupPromiseCache.set(key,promise);try{return await promise}finally{borderGroupPromiseCache.delete(key)}}
export function makeCountryHighlight(data,radius=1.012){return textureGlobe(data,radius,{fill:'rgba(255,20,147,.42)',stroke:'rgba(255,20,147,1)',lineWidth:2,size:4096})}
export function disposeLineGroup(group){if(!group)return;group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose()}if(o.userData?.__texture)o.userData.__texture.dispose()})}
export function timelineCachedProgress(){return 0}
export function paleogeographyAge(year){return Math.max(0,-year/1e6)}
