import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.161.0/examples/jsm/controls/OrbitControls.js';
import {TimeController} from './time_controller.js';
import {fragmentShader,vertexShader,atmosphereFragment,atmosphereVertex} from './shaders.js';
import {loadModernCountryBorders,loadPaleoCoastlines,loadPaleoLand,disposeLineGroup} from './geography.js';
const canvas=document.querySelector('#globe');
const loading=document.querySelector('#loading');
const status=document.querySelector('#status');
const debugButton=document.querySelector('#debugButton');
const debugPanel=document.querySelector('#debugPanel');
const debugLog=document.querySelector('#debugLog');
const debugClose=document.querySelector('#debugClose');
const debugEntries=[];
const startedAt=performance.now();
function debug(message,type='info'){const text=`[+${((performance.now()-startedAt)/1000).toFixed(2)}s] ${message}`;debugEntries.push({text,type});if(debugEntries.length>300)debugEntries.shift();if(debugLog){const line=document.createElement('div');line.className=`debug-entry ${type}`;line.textContent=text;debugLog.appendChild(line);debugLog.scrollTop=debugLog.scrollHeight}}
function installConsoleCapture(){const originalError=console.error.bind(console),originalWarn=console.warn.bind(console);console.error=(...args)=>{debug(args.map(x=>x instanceof Error?x.stack||x.message:String(x)).join(' '),'error');originalError(...args)};console.warn=(...args)=>{debug(args.map(String).join(' '),'warn');originalWarn(...args)}}
installConsoleCapture();
debug('Booting InTheGlobe');
debug(`Browser: ${navigator.userAgent}`);
debug(`WebGL canvas: ${canvas ? 'found' : 'MISSING'}`);
debugButton?.addEventListener('click',()=>{debugPanel.hidden=false;debugButton.setAttribute('aria-expanded','true')});
debugClose?.addEventListener('click',()=>{debugPanel.hidden=true;debugButton.setAttribute('aria-expanded','false')});
window.addEventListener('error',e=>{debug(`Window error: ${e.message} @ ${e.filename || 'unknown'}:${e.lineno || '?'}`,'error');finishLoading('READY · DATA DEGRADED')});
window.addEventListener('unhandledrejection',e=>{debug(`Unhandled promise rejection: ${e.reason?.stack || e.reason}`,'error');finishLoading('READY · DATA DEGRADED')});
let loadingFinished=false;
function finishLoading(message='READY'){if(loadingFinished)return;loadingFinished=true;loading.classList.add('done');status.textContent=message;debug(`Loading screen dismissed: ${message}`,'ok')}
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});debug('Three.js WebGLRenderer created','ok')}catch(e){debug(`WebGLRenderer failed: ${e.stack||e}`,'error');finishLoading('WEBGL INITIALISATION FAILED');throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x01050c);const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.05,100);camera.position.set(0,0,3.05);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.045;controls.enablePan=false;controls.minDistance=1.65;controls.maxDistance=5;controls.rotateSpeed=.45;controls.zoomSpeed=.65;
const earthGroup=new THREE.Group();scene.add(earthGroup);const loader=new THREE.TextureLoader();const fallback=new THREE.DataTexture(new Uint8Array([65,105,135,255]),1,1,THREE.RGBAFormat);fallback.needsUpdate=true;
debug('Starting Earth texture requests');
const earth=loader.load('https://threejs.org/examples/textures/planets/earth_atmos_2048.jpg',t=>{t.colorSpace=THREE.SRGBColorSpace;debug('Earth diffuse texture loaded','ok')},undefined,e=>debug(`Earth diffuse texture failed: ${e?.message||e}`,'error'));const normal=loader.load('https://threejs.org/examples/textures/planets/earth_normal_2048.jpg',()=>debug('Earth normal map loaded','ok'),undefined,e=>debug(`Earth normal map failed: ${e?.message||e}`,'error'));const specular=loader.load('https://threejs.org/examples/textures/planets/earth_specular_2048.jpg',()=>debug('Earth specular map loaded','ok'),undefined,e=>debug(`Earth specular map failed: ${e?.message||e}`,'error'));
const uniforms={uYear:{value:2026},uHeat:{value:1},uLight:{value:new THREE.Vector3(-.7,.35,.55).normalize()},uEarth:{value:earth||fallback},uNormal:{value:normal},uSpecular:{value:specular}};
const modernGlobe=new THREE.Mesh(new THREE.SphereGeometry(1,192,128),new THREE.ShaderMaterial({vertexShader,fragmentShader,uniforms}));earthGroup.add(modernGlobe);const paleoOcean=new THREE.Mesh(new THREE.SphereGeometry(.999,128,96),new THREE.MeshStandardMaterial({color:0x0a3d63,roughness:.35,metalness:.05}));paleoOcean.visible=false;earthGroup.add(paleoOcean);const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.045,128,80),new THREE.ShaderMaterial({vertexShader:atmosphereVertex,fragmentShader:atmosphereFragment,transparent:true,side:THREE.BackSide,depthWrite:false,blending:THREE.AdditiveBlending}));earthGroup.add(atmosphere);
const starGeo=new THREE.BufferGeometry(),stars=[];for(let i=0;i<1800;i++){const r=12+Math.random()*18,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);stars.push(r*Math.sin(b)*Math.cos(a),r*Math.cos(b),r*Math.sin(b)*Math.sin(a))}starGeo.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xffffff,size:.035,sizeAttenuation:true,transparent:true,opacity:.55})));
let countryBorders=null,paleoLines=null,paleoLand=null,lastPaleoSlice=null,requestSerial=0,time=null;
const countryToggle=document.querySelector('#borders');
async function updateGeography(year){const serial=++requestSerial;const historical=year<-10000;const future=year>2026;debug(`Geography update requested for year ${year}`);modernGlobe.visible=!historical;paleoOcean.visible=historical;atmosphere.visible=document.querySelector('#atmosphere').checked;if(countryBorders)countryBorders.visible=!!countryToggle.checked&&!historical&&!future;if(future){status.textContent='SPECULATIVE FUTURE · PANGEA ULTIMA SCENARIO';if(paleoLines)paleoLines.visible=false;if(paleoLand)paleoLand.visible=false;debug('Future scenario selected (speculative)');return}if(!historical){if(paleoLines)paleoLines.visible=false;if(paleoLand)paleoLand.visible=false;status.textContent=`MODERN EARTH · ${Math.round(year).toLocaleString()} CE`;debug('Using modern Earth view');return}const ageMa=Math.round((-year/1e6)*2)/2;const sliceYear=-ageMa*1e6;if(sliceYear===lastPaleoSlice){if(paleoLines)paleoLines.visible=true;if(paleoLand)paleoLand.visible=true;status.textContent=`CAO2024 RECONSTRUCTION · ${ageMa.toLocaleString()} Ma`;debug(`Reused cached paleogeography slice ${ageMa} Ma`);return}status.textContent=`RECONSTRUCTING · ${ageMa.toLocaleString()} Ma`;debug(`Fetching CAO2024 paleogeography for ${ageMa} Ma`);try{const [lines,land]=await Promise.all([loadPaleoCoastlines(sliceYear,'CAO2024'),loadPaleoLand(sliceYear,'CAO2024')]);if(serial!==requestSerial){debug('Discarding stale paleogeography response','warn');disposeLineGroup(lines);disposeLineGroup(land);return}if(paleoLines){earthGroup.remove(paleoLines);disposeLineGroup(paleoLines)}if(paleoLand){earthGroup.remove(paleoLand);disposeLineGroup(paleoLand)}paleoLines=lines;paleoLand=land;earthGroup.add(paleoOcean,paleoLand,paleoLines);lastPaleoSlice=sliceYear;paleoLines.visible=true;paleoLand.visible=true;status.textContent=`CAO2024 RECONSTRUCTION · ${ageMa.toLocaleString()} Ma`;debug(`CAO2024 reconstruction loaded for ${ageMa} Ma`,'ok')}catch(e){debug(`Paleogeography unavailable: ${e.stack||e}`,'error');status.textContent='PALEOGEOGRAPHY DATA UNAVAILABLE'}}
let pendingTimer=0;time=new TimeController({slider:document.querySelector('#timeline'),yearInput:document.querySelector('#yearInput'),yearOutput:document.querySelector('#year'),epoch:document.querySelector('#epoch'),playButton:document.querySelector('#play'),onChange:y=>{uniforms.uYear.value=y;clearTimeout(pendingTimer);pendingTimer=setTimeout(()=>updateGeography(y),90)}});debug('Time controller initialised','ok');
loadModernCountryBorders().then(g=>{countryBorders=g;earthGroup.add(g);countryBorders.visible=countryToggle.checked&&time.year>=-10000&&time.year<=2026;debug('Modern country boundaries loaded','ok')}).catch(e=>debug(`Country boundary data unavailable: ${e.stack||e}`,'error'));
updateGeography(2026).finally(()=>finishLoading('MODERN EARTH · 2,026 CE'));
setTimeout(()=>{if(!loadingFinished){debug('4-second safety timeout reached; revealing app','warn');finishLoading('MODERN EARTH · 2,026 CE')}},4000);
document.querySelector('#heat').addEventListener('change',e=>uniforms.uHeat.value=e.target.checked?1:0);document.querySelector('#terrain').addEventListener('change',()=>{});document.querySelector('#atmosphere').addEventListener('change',e=>atmosphere.visible=e.target.checked);document.querySelector('#jumpPresent').addEventListener('click',()=>time.setYear(2026));countryToggle.addEventListener('change',()=>{if(countryBorders)countryBorders.visible=countryToggle.checked&&time.year>=-10000&&time.year<=2026});const hud=document.querySelector('#hud');document.querySelector('#collapse').addEventListener('click',()=>hud.classList.add('hidden'));document.querySelector('#dock').addEventListener('click',()=>hud.classList.remove('hidden'));canvas.addEventListener('dblclick',()=>{controls.reset();camera.position.set(0,0,3.05)});
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}resize();window.addEventListener('resize',()=>{renderer.setPixelRatio(Math.min(devicePixelRatio,2));resize()});function frame(now){time.update(now);controls.update();renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);debug('Render loop started','ok');
