import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TimeController,sliderToYear,yearToSlider,formatYear,PRESENT_YEAR,yearToGeologicalAgeMa} from './time_controller.js';
import {staticPolygons,coastlines,assignPlateIds,reconstructPoints,currentEulerPerMa,featurePid,MODEL} from './gplates_client.js';
import {COUNTRIES} from './country_tracker.js';
import {loadCountries,buildCountryLayer,findCountry} from './country_renderer.js';

const canvas=document.querySelector('#globe');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x04070b);
const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.01,20);camera.position.set(0,0,3.15);
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=1.3;controls.maxDistance=8;
scene.add(new THREE.AmbientLight(0xffffff,.65));const sun=new THREE.DirectionalLight(0xffffff,2.0);sun.position.set(4,2,5);scene.add(sun);

const ocean=new THREE.Mesh(new THREE.SphereGeometry(1,128,64),new THREE.MeshPhongMaterial({color:0x123a52,shininess:12}));scene.add(ocean);
const overlays=new THREE.Group();scene.add(overlays);
const countryOverlay=new THREE.Group();scene.add(countryOverlay);

const timeline=document.querySelector('#timeline'),yearInput=document.querySelector('#yearInput'),era=document.querySelector('#era'),play=document.querySelector('#play'),status=document.querySelector('#status'),countrySelect=document.querySelector('#country');
COUNTRIES.forEach((c,i)=>{const o=document.createElement('option');o.value=i;o.textContent=c.name;countrySelect.appendChild(o)});countrySelect.value='0';
let followedCountry=null,countryPid=null,countryEuler=null,requestSerial=0,pendingRender=null,plateEulerCache=new Map(),modernCountries=null;

const R=1.012;function llv(lon,lat,r=R){const a=lat*Math.PI/180,b=lon*Math.PI/180,c=Math.cos(a);return new THREE.Vector3(r*c*Math.cos(b),r*Math.sin(a),r*c*Math.sin(b));}
function rotVec(v,euler,ma){const axis=llv(euler.lon,euler.lat,1).normalize();const q=new THREE.Quaternion().setFromAxisAngle(axis,THREE.MathUtils.degToRad(-euler.angleDegPerMa*ma));return v.clone().applyQuaternion(q)}
function clearGroup(g){while(g.children.length){const c=g.children.pop();c.geometry?.dispose?.();c.material?.dispose?.()}}
function polygonGroup(coords,color){const g=new THREE.Group();if(!coords?.length)return g;for(const ring of coords){if(!ring||ring.length<2)continue;const pts=ring.map(([lon,lat])=>llv(lon,lat));g.add(new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity:.96})))}return g}
function featureToGroup(feature,color){const g=new THREE.Group(),geom=feature.geometry;if(!geom)return g;const polys=geom.type==='Polygon'?[geom.coordinates]:geom.type==='MultiPolygon'?geom.coordinates:[];for(const poly of polys)g.add(polygonGroup(poly,color));return g}
function colorForPid(pid){return new THREE.Color().setHSL((Math.abs(pid)*.61803398875)%1,.32,.58)}
function transformFeatureFuture(feature,eulers,years){const e=eulers.get(featurePid(feature));if(!e)return feature;const clone={...feature,geometry:{...feature.geometry,coordinates:structuredClone(feature.geometry.coordinates)}};const t=x=>{if(Array.isArray(x)&&typeof x[0]==='number'){const a=rotVec(llv(x[0],x[1],1),e,years);return[THREE.MathUtils.radToDeg(Math.atan2(a.z,a.x)),THREE.MathUtils.radToDeg(Math.asin(THREE.MathUtils.clamp(a.y,-1,1)))]}return x.map(t)};clone.geometry.coordinates=t(clone.geometry.coordinates);return clone}
async function buildHistorical(ageMa){const serial=++requestSerial;status.textContent=`Loading ${MODEL} reconstruction at ${ageMa.toFixed(2)} Ma…`;try{const[plates,coast]=await Promise.all([staticPolygons(ageMa),coastlines(ageMa)]);if(serial!==requestSerial)return;clearGroup(overlays);clearGroup(countryOverlay);for(const f of plates.features||[])overlays.add(featureToGroup(f,colorForPid(featurePid(f))));const cg=new THREE.Group();for(const f of coast.features||[])cg.add(featureToGroup(f,0xc8c3ad));cg.scale.setScalar(1.003);overlays.add(cg);if(ageMa<.001&&modernCountries){const selected=followedCountry?findCountry(modernCountries,followedCountry.name):null;countryOverlay.add(buildCountryLayer(modernCountries,{selectedIso:selected?.properties?.ISO_A3||selected?.properties?.ADM0_A3||null}));}status.textContent=`${MODEL} · geological reconstruction · country borders are shown only for the modern Earth`;pendingRender=null}catch(e){console.error(e);status.textContent='GPlates data request failed; check network access.';pendingRender=null}}
async function ensureFutureEulers(features){for(const pid of [...new Set((features.features||[]).map(featurePid).filter(Boolean))])if(!plateEulerCache.has(pid)){try{plateEulerCache.set(pid,await currentEulerPerMa(pid))}catch{}}return plateEulerCache}
async function buildFuture(futureMa){const serial=++requestSerial;status.textContent='Building future from present-day Euler velocities…';try{const base=await staticPolygons(0);if(serial!==requestSerial)return;const eulers=await ensureFutureEulers(base);clearGroup(overlays);clearGroup(countryOverlay);for(const f of base.features||[])overlays.add(featureToGroup(transformFeatureFuture(f,eulers,futureMa),colorForPid(featurePid(f))));status.textContent='Future · constant present-day Euler rotation extrapolation';pendingRender=null}catch(e){console.error(e);status.textContent='Future reconstruction failed; check network access.';pendingRender=null}}
async function selectCountry(){const c=COUNTRIES[Number(countrySelect.value)];followedCountry=c.name==='None'?null:c;if(!followedCountry){countryPid=null;countryEuler=null;clearGroup(countryOverlay);return}try{const ids=await assignPlateIds([c.lat],[c.lon]);countryPid=Array.isArray(ids)?Number(ids[0]):Number(ids?.plate_ids?.[0]??ids?.[0]);if(countryPid)countryEuler=await currentEulerPerMa(countryPid)}catch{countryPid=null;countryEuler=null}clearGroup(countryOverlay);if(modernCountries&&yearToGeologicalAgeMa(tc.year)<.001){const f=findCountry(modernCountries,followedCountry.name);if(f)countryOverlay.add(buildCountryLayer(modernCountries,{selectedIso:f.properties?.ISO_A3||f.properties?.ADM0_A3||null}))}}
const tc=new TimeController({onChange:calendarYear=>{yearInput.value=Math.round(calendarYear);era.textContent=formatYear(calendarYear);timeline.value=yearToSlider(calendarYear)*1e6;scheduleRender(yearToGeologicalAgeMa(calendarYear))}});
function scheduleRender(ageMa){const key=Math.round(ageMa*1000)/1000;if(pendingRender===key)return;pendingRender=key;if(ageMa>=0)buildHistorical(Math.min(600,Math.max(0,ageMa)));else buildFuture(-ageMa)}
timeline.addEventListener('input',()=>{});timeline.addEventListener('change',()=>tc.setYear(sliderToYear(Number(timeline.value)/1e6)));document.querySelector('#go').onclick=()=>tc.setYear(Number(yearInput.value)||0);yearInput.addEventListener('keydown',e=>{if(e.key==='Enter')tc.setYear(Number(yearInput.value)||0)});play.onclick=()=>{const playing=tc.toggle();play.textContent=playing?'❚❚ Pause':'▶ Play';play.classList.toggle('active',playing)};document.querySelector('#stepBack').onclick=()=>tc.setYear(tc.year-1000000);document.querySelector('#stepForward').onclick=()=>tc.setYear(tc.year+1000000);document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{tc.setSpeed(Number(b.dataset.speed));document.querySelectorAll('[data-speed]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelector('[data-speed="1"]').classList.add('active');countrySelect.onchange=selectCountry;document.querySelector('#heatmap').onchange=()=>{};document.querySelector('#releaseFollow').onclick=()=>{countrySelect.value='0';followedCountry=null;countryPid=null;countryEuler=null;clearGroup(countryOverlay)};const panelToggle=document.querySelector('#panelToggle');panelToggle.onclick=()=>{const hud=document.querySelector('#hud');hud.classList.toggle('minimised');const open=!hud.classList.contains('minimised');panelToggle.setAttribute('aria-expanded',String(open));panelToggle.textContent=open?'⌄':'⌃'};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});function render(){controls.update();if(followedCountry&&tc.playing){let desired=llv(followedCountry.lon,followedCountry.lat,2.4);if(tc.year>PRESENT_YEAR&&countryEuler)desired.copy(rotVec(llv(followedCountry.lon,followedCountry.lat,1),countryEuler,(tc.year-PRESENT_YEAR)/1e6).normalize().multiplyScalar(2.4));camera.position.lerp(desired,.06);controls.target.lerp(desired.clone().normalize().multiplyScalar(.92),.06)}renderer.render(scene,camera);requestAnimationFrame(render)}
(async()=>{try{modernCountries=await loadCountries()}catch(e){console.error(e)}yearInput.value=PRESENT_YEAR;era.textContent=formatYear(PRESENT_YEAR);timeline.value=yearToSlider(PRESENT_YEAR)*1e6;scheduleRender(0);tc.start();requestAnimationFrame(render)})();
